### ISSUE TITLE
'squelize-admin' is not in the npm registry

### ISSUE THREAD

**Issue by lanesawyer** [sequelize/sequelize-admin#3]
I'm trying to use this module but it fails on "npm install" because it's not in the registry. It looks like all your other ones are published. Can you publish this one as well?

**Comment by eranimo** [comment]
It's sequelize-admin, not squelize-admin. Maybe that's it?

**Comment by sdepold** [comment]
(y)

**Comment by sdepold** [comment]
:+1:

**Comment by lanesawyer** [comment]
Haha that's probably it. I'm not a smart man.
